### ISSUE TITLE
Create stamp rally

### ISSUE THREAD

**Issue by yhay81** [cc4-butterfly/stamp-rally#11]
As Shigeru, I want to create a new stamp rally, so that my son can do the new rally and enjoy it.

**Acceptance Criteria**

- [ ] On the top page, you can find the + button.
- [ ] After clicking it, a new page appears and there is a name, and description input.
- [ ] And there are also somethings to add locations.

**Comment by a-ogilvie** [comment]
Changed this to a front-end web app.
